/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static Main.Crucigrama.varas;
import java.awt.GridLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import model.GridButtom;
import model.Person;

/**
 *
 * @author Steven
 */
public class Tablero extends javax.swing.JFrame {
    
    private Person person;
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }
     private void initPanel() {

        GridLayout grid = new GridLayout(7, 7);
        pnTablero.setLayout(grid);
                for (int i = 0; i < varas.getPersonCounter(); i++) {
            GridButtom newGridButtom = new GridButtom(varas.getPerson(i));
            pnTablero.add(newGridButtom);
            newGridButtom.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if (evt.getSource() == newGridButtom) {
                        person = newGridButtom.getPerson();
                    }
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTablero = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnTableroLayout = new javax.swing.GroupLayout(pnTablero);
        pnTablero.setLayout(pnTableroLayout);
        pnTableroLayout.setHorizontalGroup(
            pnTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        pnTableroLayout.setVerticalGroup(
            pnTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnTablero;
    // End of variables declaration//GEN-END:variables
}
